name = "Claudia Rodríguez"
rol = "Digital Business Specialist"
email = "claudiarodriguezcalo@gmail.com"
phone = "+34 606 409 236"
location = "Madrid, Spain"
avatar = "./config/assets/avatars/avatar-2.png"
username = "clauclacla" # <-- github user name
presentation = """
I'm a Digital Business specialist with a diverse background in operations, marketing, and project management. With +4 years of cross-functional teams management and project planning, I have a data-driven approach, autonomy and entrepreneurial mindset. 

I'm a lifelong learner, passionate about technology implementation and Business Intelligence.

"""
