[[doing]]
title = "Operations"
icon = "./config/assets/icons/mobile.svg"
text = "Build the As-Is model and design the To-Be model that reaches operational efficiency"

[[doing]]
title = "Consulting"
icon = "./config/assets/icons/code.svg"
text = "Problem solving and data driven approach for decision making"

[[doing]]
title = "Marketing Automation"
icon = "./config/assets/icons/compass.svg"
text = "Marketing Campaigns, Automation and Analytics experience"

[[doing]]
title = "Business Intelligence"
icon = "./config/assets/icons/laptop-code.svg"
text = "Leverage data and statistics to achieve business goals"
