# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"

logo-linkedin = "https://www.linkedin.com/claudiarodriguezcalo/"
logo-github = "https://github.com/clauclacla"
