############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[Technical Skills]
python = "./config/assets/icons/python.svg"
pandas = "./config/assets/icons/pandas.svg"
ai = "./config/assets/icons/ai.svg"
jupyter = "./config/assets/icons/jupyter.svg"
linux = "./config/assets/icons/linux.svg"
Google Analytics = ""
Google Tag Manager = ""
Zoho One = ""
WordPress = ""
Mailchimp = ""
Zapier = ""
Make = ""
Sendible = ""
Excel (advanced) = ""
Power Point = ""
Keynote = ""
SQL = ""
Tableau = ""
GPT+ = ""

