############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[Technical Skills]
python = "./config/assets/icons/python.svg"
office = "./config/assets/icons/microsoft365.png"
excel = "./config/assets/icons/excel.png"
pandas = "./config/assets/icons/pandas.svg"
postgree = "./config/assets/icons/postgree.png"
ai = "./config/assets/icons/ai.svg"
jupyter = "./config/assets/icons/jupyter.svg"
linux = "./config/assets/icons/linux.svg"
Google_Analytics = "./config/assets/icons/google-analytics.svg"
Google_Tag_Manager = "./config/assets/icons/google-tag-manager.svg"
Zoho_One = "./config/assets/icons/zoho.png"
WordPress = "./config/assets/icons/wordpress.png"
Mailchimp = "./config/assets/icons/"
Zapier = "./config/assets/icons/"
Make = "./config/assets/icons/"
Sendible = "./config/assets/icons/"
Excel = "./config/assets/icons/"
Power_Point = "./config/assets/icons/"
Keynote = "./config/assets/icons/"
SQL = "./config/assets/icons/"
Tableau = "./config/assets/icons/"
GPT4 = "./config/assets/icons/"

